-- Test database
CREATE TABLE IF NOT EXISTS tests (STRING TEXT NOT NULL, RESULT INT);
-- Network database
CREATE TABLE IF NOT EXISTS network (NAME TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS layer (NETWORK_ID INT);
CREATE TABLE IF NOT EXISTS neuron (LAYER_ID INT, WEIGHT REAL DEFAULT 0.5);
CREATE TABLE IF NOT EXISTS network_history (NETWORK_NAME TEXT NOT NULL, PARENT TEXT);
INSERT INTO network ('Annabelle');
INSERT INTO network_history ('Annabelle', NULL);
-- Results detabase
CREATE TABLE IF NOT EXISTS results (NETWORK_ID INT, TEST_ID INT, RESULT INT);